version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  versioning-strategy: increase
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: react-final-form
    versions:
    - 6.5.2
  - dependency-name: enzyme-to-json
    versions:
    - 3.6.1
  - dependency-name: "@dhis2/app-runtime"
    versions:
    - 2.6.1
    - 2.7.0
    - 2.7.1
    - 2.8.0
  - dependency-name: "@dhis2/cli-app-scripts"
    versions:
    - 5.5.1
    - 5.5.2
    - 5.6.0
    - 5.7.0
    - 5.7.2
    - 5.7.3
    - 5.7.4
  - dependency-name: whatwg-fetch
    versions:
    - 3.5.0
    - 3.6.1
  - dependency-name: "@dhis2/cli-style"
    versions:
    - 7.3.0
